name: Build

on: push

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-18.04, windows-latest, macos-latest] # skip windows 
        os: [ubuntu-20.04, macos-10.15, macos-11]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1


      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.1.1

      - name: Build wheels
        env:
          CIBW_SKIP: "pp* cp36-manylinux_i686"
          CIBW_BEFORE_BUILD_LINUX: "/bin/bash cibuild/linux_steps.sh"
          CIBW_BEFORE_BUILD_MACOS: "/bin/bash cibuild/macos_steps.sh"
          CIBW_TEST_COMMAND: "cd {project}/pyosmium/test && rm -rf ../build && python -m nose"
          CIBW_TEST_REQUIRES: nose mock shapely==1.7.1
          CIBW_TEST_SKIP: "cp310-*" # cannot install shapely

        run: |
          python -m cibuildwheel --output-dir wheelhouse pyosmium

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
