name: Build

on: push

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-18.04, windows-latest, macos-latest] # skip windows 
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1


      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.6.4

      - name: Build wheels
        env:
          CIBW_SKIP: "cp27-* cp35-* pp* cp39-manylinux*"
          CIBW_BEFORE_BUILD_LINUX: "/bin/bash cibuild/linux_steps.sh"
          CIBW_BEFORE_BUILD_MACOS: "/bin/bash cibuild/macos_steps.sh"
          CIBW_TEST_COMMAND: "cd {project}/pyosmium/test && rm -rf ../build && python -m nose"
          CIBW_BEFORE_TEST: "pip install nose mock shapely"

        run: |
          python -m cibuildwheel --output-dir wheelhouse pyosmium

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

