name: Build

on: push

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-18.04, windows-latest, macos-latest] # skipp windows and mac for now
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1


      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.6.4

      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y

      - name: Build wheels
        env:
          CIBW_SKIP: "cp27-* cp35-* pp*"
          CIBW_BEFORE_BUILD_LINUX: "/bin/bash /project/cibuild/linux_steps.sh"

        run: |
          python -m cibuildwheel --output-dir wheelhouse pyosmium

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

